POST localhost:8000/monsters
content-type: application/json

{
    "name": "Diablos",
    "description": "Big idiot",
    "species": "flying wyvern",
	"elements": ["fire"],
    "weaknesses": [
    	{
    		"element": "fire",
    		"stars": 1,
    		"condition": "covered in gas"
    	}
    ],
    "resistances": [
    	{
    		"element": "ice"
    	}
    ],
    "images": [
    	{
    		"name": "big bad monster",
    		"url": "https://www.google.com"
    	}
    ],
    "ailments": [
    	{
    		"name": "Blastblight",
    		"actions": [
    			"nullbery",
    			"dodge"
    		]
    	}],
    "size": "large"
}
